databases:
  - name: module-five
    databaseName: module-five
    user: module_five_user

services:
  - type: web
    name: gilbert
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: module-five
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false